// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_jEoKtsoQlnkWENAK89HAsuXBVkhvY_s',
    appId: '1:772324431093:web:5fc387809e29e86d2fe1bc',
    messagingSenderId: '772324431093',
    projectId: 'fix-appliance-crm',
    authDomain: 'fix-appliance-crm.firebaseapp.com',
    storageBucket: 'fix-appliance-crm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE4nxOyA1Qwp58yDzyzInXRxq3jIB1zvA',
    appId: '1:772324431093:android:afff73faed16a00f2fe1bc',
    messagingSenderId: '772324431093',
    projectId: 'fix-appliance-crm',
    storageBucket: 'fix-appliance-crm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfoaSmrZwSBJ4Hz3TZ8wTMAIoC0WNwHrg',
    appId: '1:772324431093:ios:c906214ef15ddd782fe1bc',
    messagingSenderId: '772324431093',
    projectId: 'fix-appliance-crm',
    storageBucket: 'fix-appliance-crm.firebasestorage.app',
    iosClientId:
        '772324431093-4c3i2h5mp922o9gnlnoaq2jg4i5esocr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixApplianceCrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfoaSmrZwSBJ4Hz3TZ8wTMAIoC0WNwHrg',
    appId: '1:772324431093:ios:c906214ef15ddd782fe1bc',
    messagingSenderId: '772324431093',
    projectId: 'fix-appliance-crm',
    storageBucket: 'fix-appliance-crm.firebasestorage.app',
    iosClientId:
        '772324431093-4c3i2h5mp922o9gnlnoaq2jg4i5esocr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixApplianceCrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_jEoKtsoQlnkWENAK89HAsuXBVkhvY_s',
    appId: '1:772324431093:web:249e7ec3fc1462e02fe1bc',
    messagingSenderId: '772324431093',
    projectId: 'fix-appliance-crm',
    authDomain: 'fix-appliance-crm.firebaseapp.com',
    storageBucket: 'fix-appliance-crm.firebasestorage.app',
  );
}
